services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    c975L\UiBundle\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity}'

    c975L\UiBundle\Service\StylesheetProvider:
        tags:
            - { name: 'ui.stylesheet', priority: 100 }
            - { name: 'ui.management_stylesheet', priority: 100 }

    c975L\UiBundle\Service\ScriptProvider:
        tags:
            - { name: 'ui.script', priority: 100 }
            - { name: 'ui.admin_script', priority: 100 }

    # Ui Blocks
    ui.block.article:
        class: stdClass
        tags:
            - name: ui.block
              kind: article
              label: "label.block_article"
              description: "label.block_article_description"
              form: c975L\UiBundle\Form\Block\ArticleType
              template: '@c975LUi/blocks/Article.html.twig'
              category: 'label.category_elements'
              media_types: 'image/*'
              media_multi_upload: true
              priority: 90
              pickable: true
              cacheable: true

    ui.block.alert:
        class: stdClass
        tags:
            - name: ui.block
              kind: alert
              label: "label.block_alert"
              description: "label.block_alert_description"
              form: c975L\UiBundle\Form\Block\AlertType
              template: '@c975LUi/blocks/Alert.html.twig'
              category: 'label.category_elements'
              priority: 70
              pickable: true
              cacheable: true

    ui.block.audio:
        class: stdClass
        tags:
            - name: ui.block
              kind: audio
              label: "label.block_audio"
              description: "label.block_audio_description"
              form: c975L\UiBundle\Form\Block\AudioType
              template: '@c975LUi/blocks/Audio.html.twig'
              category: 'label.category_media'
              media_types: 'audio/*'
              priority: 70
              pickable: true
              cacheable: true

    ui.block.banner_title:
        class: stdClass
        tags:
            - name: ui.block
              kind: banner_title
              label: "label.block_banner_title"
              description: "label.block_banner_title_description"
              form: c975L\UiBundle\Form\Block\BannerTitleType
              template: '@c975LUi/blocks/BannerTitle.html.twig'
              category: 'label.category_media'
              media_types: 'image/*'
              media_required: true
              priority: 90
              pickable: true
              cacheable: true

    ui.block.button:
        class: stdClass
        tags:
            - name: ui.block
              kind: button
              label: "label.block_button"
              description: "label.block_button_description"
              form: c975L\UiBundle\Form\Block\ButtonType
              template: '@c975LUi/blocks/Button.html.twig'
              category: 'label.category_elements'
              priority: 80
              pickable: true
              cacheable: true

    ui.block.card:
        class: stdClass
        tags:
            - name: ui.block
              kind: card
              label: "label.block_card"
              description: "label.block_card_description"
              form: c975L\UiBundle\Form\Block\CardType
              template: '@c975LUi/blocks/Card.html.twig'
              category: 'label.category_elements'
              media_types: 'image/*'
              priority: 100
              pickable: true
              cacheable: true

    ui.block.image:
        class: stdClass
        tags:
            - name: ui.block
              kind: image
              label: "label.block_image"
              description: "label.block_image_description"
              form: c975L\UiBundle\Form\Block\ImageType
              template: '@c975LUi/blocks/Image.html.twig'
              category: 'label.category_media'
              media_types: 'image/*'
              priority: 100
              pickable: true
              cacheable: true

    ui.block.progress_bar:
        class: stdClass
        tags:
            - name: ui.block
              kind: progress_bar
              label: "label.block_progress_bar"
              description: "label.block_progress_bar_description"
              form: c975L\UiBundle\Form\Block\ProgressBarType
              template: '@c975LUi/blocks/ProgressBar.html.twig'
              category: 'label.category_elements'
              priority: 60
              pickable: true
              cacheable: true

    ui.block.rich_snippet:
        class: stdClass
        tags:
            - name: ui.block
              kind: rich_snippet
              label: "label.block_rich_snippet"
              description: "label.block_rich_snippet_description"
              form: c975L\UiBundle\Form\Block\RichSnippetType
              template: '@c975LUi/blocks/RichSnippet.html.twig'
              category: 'label.category_seo'
              pickable: true
              cacheable: true

    ui.block.slider:
        class: stdClass
        tags:
            - name: ui.block
              kind: slider
              label: "label.block_slider"
              description: "label.block_slider_description"
              form: c975L\UiBundle\Form\Block\SliderType
              template: '@c975LUi/blocks/Slider.html.twig'
              category: 'label.category_media'
              media_types: 'image/*,video/*'
              media_multi_upload: true
              priority: 90
              pickable: true
              cacheable: true

    ui.block.text_readmore:
        class: stdClass
        tags:
            - name: ui.block
              kind: text_readmore
              label: "label.block_text_readmore"
              description: "label.block_text_readmore_description"
              form: c975L\UiBundle\Form\Block\ReadmoreType
              template: '@c975LUi/blocks/TextReadmore.html.twig'
              category: 'label.category_text'
              priority: 90
              pickable: true
              cacheable: true

    ui.block.text_section:
        class: stdClass
        tags:
            - name: ui.block
              kind: text_section
              label: "label.block_text_section"
              description: "label.block_text_section_description"
              form: c975L\UiBundle\Form\Block\TextSectionType
              template: '@c975LUi/blocks/TextSection.html.twig'
              category: 'label.category_text'
              priority: 100
              pickable: true
              cacheable: true

    ui.block.video:
        class: stdClass
        tags:
            - name: ui.block
              kind: video
              label: "label.block_video"
              description: "label.block_video_description"
              form: c975L\UiBundle\Form\Block\VideoType
              template: '@c975LUi/blocks/Video.html.twig'
              category: 'label.category_media'
              media_types: 'video/*'
              priority: 80
              pickable: true
              cacheable: true

    ui.block.video_iframe:
        class: stdClass
        tags:
            - name: ui.block
              kind: video_iframe
              label: "label.block_video_iframe"
              description: "label.block_video_iframe_description"
              form: c975L\UiBundle\Form\Block\VideoIframeType
              template: '@c975LUi/blocks/VideoIframe.html.twig'
              category: 'label.category_media'
              priority: 60
              pickable: true
              cacheable: true